import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>Home is server sided with one client sided component</div>
        <div>
          Other components are all client sided except for the layout component
          that wraps all other components
        </div>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            gap: "2rem",
          }}
        >
          <Link href="/home">Home</Link>
          <Link href="/pageB">Page B</Link>
          <Link href="/pageC">Page C</Link>
          <Link href="/pageD">Page D</Link>
          <Link href="/client">Client Side</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
