import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ComponentA from "./asvasd/ComponentA";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ComponentA>{children}</ComponentA>
      </body>
    </html>
  );
}
